### ISSUE TITLE
Serializacija WCF

### ISSUE THREAD

**Issue by vukisic** [vukisic/SCADA_Project#11]
Bug:
Problem kada se salju klase preko WCF-a, ne mogu se trenutno serializovati. 
Porenuto u sledecem redosledu
![image](https://user-images.githubusercontent.com/25881728/101991299-fefd0100-3cab-11eb-92b7-16a7d1912d20.png)

Screenshot
![Screenshot (32)](https://user-images.githubusercontent.com/25881728/101991203-6cf4f880-3cab-11eb-8224-dd7dbd19c5f9.png)

**Comment by DaniloNovakovic** [comment]
Ovo se odnosi na branch feature/nms-transaction
