### ISSUE TITLE
Interaktivna šema na GUI strani

### ISSUE THREAD

**Issue by DaniloNovakovic** [vukisic/SCADA_Project#50]
Treba predstaviti šemu slično kao na slici prikazanoj [ovde](https://github.com/vukisic/SCADA_Project/wiki/Shema)

Ideja za rešavanje problema:

1. Mapirati dobijen model na stukturu podataka u vidu stabla
1. Dodeliti svakom čvoru u stablu referencu na odgovarajuću svg sliku (recimo putem neke mapper komponente koja zna da mapira tip podatka na sliku)
1. Prikazati ovo stablo na ekranu nekako gde bi svaki čvor bio prikazan putem svg slike

Nakon uspešno urađenih koraka je potrebno dodati i "onClick" funkcionalnost, gde bi mogli elementi da se pale/gase putem klika.  Ideja jeste da se gašenjem nekog čvora takođe ugase i svi njegovi potomci.

Moguće je korišćenje i eksternih biblioteka za ovo tako da bi valjalo i ovu opciju istražiti

**Comment by vukisic** [comment]
potred toga što bi elementi (prekidači i rastavljači) na "onClick" trebali da se pale i gase, potrebno je na "onClick" regulacionog trensformatora obezbediti mogućnost izbora položaja regulacione sklopke.
