### ISSUE TITLE
Sinhronizacija merenja i elemenata na šemi

### ISSUE THREAD

**Issue by DaniloNovakovic** [vukisic/SCADA_Project#61]
Potrebno je sinhronizovani merenja dobijena od skade sa elementima na šemi u GUI strani

U suštini:
- Implementirati `UpdateMeasurements` unutar `GraphicsViewModel` klase
- Prilikom onClick nad elementima (gašenje, paljenje, modifikacija u formi...) je potrebno takođe poslati komandu putem NServiceBus ka skadi

**Comment by vukisic** [comment]
- Potrebno je prikazati i merenja pored samih elementa (napon i struja transformatora, pozicija teretnog menjača).
- Ako pumpa radi (njen flow je > 0) treba signalizirati da radi (npr. ako radi zelena je, ako ne radi crvena je).
