### ISSUE TITLE
Bug: Boja okvira od elemenata nije sinhronizovana sa merenjima

### ISSUE THREAD

**Issue by DaniloNovakovic** [vukisic/SCADA_Project#69]
Trenutno boja bordera elemenata nije sinhronizovana sa merenjima sa skade.

Problem je zapravo što boja bordera **ni ne treba uvek** da bude sinhronizovana sa merenjima nego samo ponekad za neke elemente. Npr. ako je roditelj isključen onda i deca trebaju da mu budu isključena (merenja treba da budu ignorisana), samo u slučaju ako je roditelj uključen merenja od dece trebaju da se uzimaju u obzirom.

Još jedan problem jeste što kada se ažurira measurement, opet nekad treba da se ažuriraju vrednosti dece (u slučaju da je roditelj disconnector ili breaker), a nekad ne (za transformator npr. - on ima više measurementa -> pod transformatorom se u kontekstu GUI-a smatra "TapChanger" + "PowerTransformator" + "TransformerWinding")

> Pod terminima "Uključen" i "Isključen" se smatra Zelena i Crvena boja bordera

Napomene za potencijalno rešenje problema:

Ovo ponašanje "nekad ovako", "nekad onako" zahteva rešenje da poseduje sledeće:
- **Single source of truth** - Vrednosti treba da reguliše sama TreeNode klasa, a aktori sa spolja treba da menjaju vrednosti putem metode (npr. UpdateMeasurement()) a ne preko polja (ovo je iz razloga što neki elementi treba da ažuriraju decu po promeni, a neki ne)
- **TreeNode treba da bude "base" klasa koju nasleđuju ostale klase** (npr. SwitchTreeNode, TransformerTreeNode, AsyncMachineTreeNode) - svaka od ovih klasa bi posedovale ponašanje sklono njima (za disconnector+breaker mogu da se iskoristi jedna klasa (npr. SwitchTreeNode) jer tehnički je ponašanje od ove dve klase identično)
- **Već postoji TreeNodeFactory klasa u kojoj je ovo moguće uraditi** - Nije potrebno menjati algoritam za iscrtavanje stabla, samo je potrebno promeniti logiku prilikom ažuriranja vrednosti, tj. implementaciju `MeasurementUpdater` klase, ili tačnije (ukoliko bi se `UpdateMeasurements` metoda iz `Item` objekta prebacila u `TreeNode` objekat gde bi njeno ponašanje bilo drugačije za svaki od tipova koji nasleđuju ovu klasu - npr. neki bi ažurirali decu, neki ne)

Rešenje / logika za ovo je delimično tu, međutim srž ovog buga se nalazi u pristupu - mešanje funkcionalne paradigme sa WPF-om (lesson learned: to dvoje ne idu zajedno nikako)

**Comment by vukisic** [comment]
Problem je rešen koristeći heuristiku poznavanja postrojenja i elemenata u njemu tako da SCADA sada vodi glavnu ulogu. Sama logika sinhronizacije je trivijalna jer je mreža radijalnog tipa i zasniva se na proveri statusa elementa u slučaju prekidačke opreme ili položaja regulacione sklopke u slučaju regulaciong transformatora. Sva logika je definisana u UpdateMeasurements klasi i lako se može prosirit nasledjivanjem bazne klase i redefinsanjem logike.

**Comment by vukisic** [comment]
Takodje ostavljena je mogućnost izbora načina prikaza u slucaju isključivanja elementa:
1. Logika gde kada se element isključi , svi down stream elementi se isključuju
2. Logika gde kada se element isključi , ostali ostaju uključeni (zeleni) ali se vizuelno vidi da je upstream element isključen i da nema protoka energije.
